server {
    listen 80;
    listen [::]:80;
    server_name ~^(?<subdomain>.+)\.tuneloom\.cfd$;

    error_log /var/log/nginx/tuneloom-error.log warn;
    access_log /var/log/nginx/tuneloom-access.log;

    location / {
        resolver 8.8.8.8;

        set $backend "https://d313i82t9xdc0u.cloudfront.net";
        set $base_path "/$subdomain";

        if ($uri = "/") {
            set $path "$base_path/index.html";
        }

        if ($uri != "/") {
            set $path "$base_path$uri";
        }

        proxy_pass $backend$path;

        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_set_header Host d313i82t9xdc0u.cloudfront.net;
    }
}
