import React from 'react';
import { File, Code, FileText, Folder } from 'lucide-react';

const FileManager = ({ files = [], selectedFile, onFileSelect }) => {

  const getFileIcon = (filename) => {
    const extension = filename.split('.').pop();
    switch (extension) {
      case 'html':
      case 'htm':
        return <FileText className="h-5 w-5 text-orange-400" />;
      case 'css':
        return <FileText className="h-5 w-5 text-blue-400" />;
      case 'js':
      case 'jsx':
        return <Code className="h-5 w-5 text-yellow-400" />;
      default:
        return <File className="h-5 w-5 text-gray-400" />;
    }
  };

  const handleFileSelect = (file) => {
    onFileSelect(file);
  };

  return (
    <div className="h-full flex bg-gradient-to-br from-[#121212] to-[#0F0F0F]">
      {/* Enhanced File list sidebar */}
      <div className="w-80 border-r border-[#2A2A2A] bg-gradient-to-b from-[#1A1A1A] to-[#121212]">
        <div className="p-4 border-b border-[#2A2A2A] bg-gradient-to-r from-[#1A1A1A] to-[#252525]">
          <div className="flex items-center justify-between">
            <h3 className="text-white font-bold flex items-center">
              <Folder className="h-5 w-5 mr-2 text-[#4ADE80]" />
              Project Files
            </h3>
            <span className="text-xs text-[#4ADE80] bg-[#4ADE80]/10 px-3 py-1 rounded-full border border-[#4ADE80]/20 font-semibold">
              {files.length} files
            </span>
          </div>
          <p className="text-[#B0B0B0] text-sm mt-1">Generated by AI</p>
        </div>
        <div className="p-3">
          {files.length === 0 ? (
            <div className="text-center py-12">
              <div className="w-16 h-16 bg-gradient-to-br from-[#4ADE80] to-[#22C55E] rounded-2xl flex items-center justify-center mx-auto mb-4">
                <Folder className="h-8 w-8 text-[#121212]" />
              </div>
              <h4 className="text-white font-semibold mb-2">No Files Yet</h4>
              <p className="text-[#B0B0B0] text-sm">Files will appear here when generated by AI</p>
            </div>
          ) : (
            <div className="space-y-2">
              {files.map((file, index) => (
                <button
                  key={index}
                  onClick={() => handleFileSelect(file)}
                  className={`w-full flex items-center p-3 rounded-xl text-left transition-all duration-200 group ${
                    selectedFile?.filename === file.filename 
                      ? 'bg-gradient-to-r from-[#4ADE80]/10 to-[#22C55E]/10 border border-[#4ADE80]/30 shadow-lg' 
                      : 'hover:bg-[#2A2A2A]/50 border border-transparent'
                  }`}
                >
                  <div className={`w-10 h-10 rounded-lg flex items-center justify-center mr-3 transition-all duration-200 ${
                    selectedFile?.filename === file.filename 
                      ? 'bg-gradient-to-br from-[#4ADE80]/20 to-[#22C55E]/20' 
                      : 'bg-[#2A2A2A] group-hover:bg-[#3A3A3A]'
                  }`}>
                    {getFileIcon(file.filename)}
                  </div>
                  <div className="flex-1 min-w-0">
                    <span className="text-[#E0E0E0] font-medium text-sm block truncate">
                      {file.filename}
                    </span>
                    <span className="text-[#B0B0B0] text-xs">
                      {file.content?.length || 0} characters
                    </span>
                  </div>
                  {selectedFile?.filename === file.filename && (
                    <div className="w-2 h-2 bg-[#4ADE80] rounded-full animate-pulse ml-2"></div>
                  )}
                </button>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Enhanced File content viewer */}
      <div className="flex-1 bg-gradient-to-br from-[#121212] to-[#0F0F0F]">
        {selectedFile ? (
          <div className="h-full flex flex-col">
            {/* Premium File Header */}
            <div className="flex items-center justify-between p-4 border-b border-[#2A2A2A] bg-gradient-to-r from-[#1A1A1A] to-[#252525]">
              <div className="flex items-center">
                <div className="w-10 h-10 bg-gradient-to-br from-[#4ADE80]/20 to-[#22C55E]/20 rounded-lg flex items-center justify-center mr-3">
                  {getFileIcon(selectedFile.filename)}
                </div>
                <div>
                  <span className="text-white font-bold text-lg">{selectedFile.filename}</span>
                  <p className="text-[#B0B0B0] text-sm">
                    {selectedFile.content?.length || 0} characters • Ready to copy or download
                  </p>
                </div>
              </div>
            </div>
            {/* Enhanced File Content */}
            <div className="flex-1 overflow-auto bg-[#0A0A0A]">
              <div className="relative">
                <pre className="p-6 text-[#E0E0E0] text-sm font-mono whitespace-pre-wrap leading-relaxed">
                  {selectedFile.content}
                </pre>
                {/* Gradient overlay for premium effect */}
                <div className="absolute inset-0 bg-gradient-to-br from-transparent via-transparent to-[#4ADE80]/5 pointer-events-none"></div>
              </div>
            </div>
          </div>
        ) : (
          <div className="h-full flex items-center justify-center p-8">
            <div className="text-center max-w-md">
              <div className="w-20 h-20 bg-gradient-to-br from-[#4ADE80] to-[#22C55E] rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-2xl">
                <File className="h-10 w-10 text-[#121212]" />
              </div>
              <h3 className="text-white text-xl font-bold mb-3">Select a File to View</h3>
              <p className="text-[#B0B0B0] leading-relaxed">
                Choose a file from the sidebar to view its content, copy it to your clipboard, or download it to your computer.
              </p>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default FileManager;
